"""Unified submission orchestrator (M1 / Section 4) — round 6.

Final design contract (round 6):

* SubmissionResult is a frozen dataclass that mirrors the public
  ``Submission`` contract plus internal ownership / idempotency
  fields.  No silent ``getattr(sub, "persona_hint", ...)`` — the
  real Submission dataclass has no such field.
* Pre-allocated ``job_id`` is generated by the orchestrator BEFORE
  any state change.  The reservation row is inserted with that
  ``job_id``; the Job record is inserted via
  ``JobRepository.submit_idempotent(job_id=...)`` (which honours the
  external id); and on crash the resume path finds the Job by id.
* The same orchestrator is the canonical entry for Web, CLI, QQ,
  benchmark.  ``direct_answer`` (``mode="direct_answer"`` or
  ``--direct-answer``) bypasses the reservation table and is allowed
  to return ``job_id=""`` when the application layer accepted the
  answer directly.
"""
from __future__ import annotations

import logging
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .idempotent_submit import (
    IdempotencyConflict, IdempotencyScopeError, NotYetOwned,
    UnauthorisedInstanceError,
    RESERVATION_STATES,
    canonical_payload, compute_fingerprint,
    reserve, acquire_ownership, mark_state, reap_expired, lookup,
    lookup_by_job,
)


_log = logging.getLogger("partner.application.orchestrator")


_VALID_INSTANCES = {"01", "02", "03", "04", "05"}


def to_submission_result(
    *,
    job_id: str,
    project_id: str,
    assigned_instance: str,
    status: str,
    route: str,
    message: str = "",
    message_id: str = "",
    request_id: str = "",
    fingerprint: str = "",
    owner_token: str = "",
    persona_hint: str = "",
    was_idempotent_hit: bool = False,
) -> "SubmissionResult":
    """Canonical converter from real Submission fields to SubmissionResult.

    Use this whenever you build a SubmissionResult so that no caller
    invents fields the Submission dataclass does not carry.
    """
    return SubmissionResult(
        job_id=str(job_id),
        assigned_instance=str(assigned_instance),
        persona_hint=str(persona_hint),
        project_id=str(project_id),
        status=str(status),
        route=str(route),
        request_id=str(request_id),
        fingerprint=str(fingerprint),
        owner_token=str(owner_token),
        was_idempotent_hit=bool(was_idempotent_hit),
    )


@dataclass(frozen=True)
class SubmissionResult:
    """Public result returned to every entry point (Web / CLI / QQ)."""
    job_id: str
    assigned_instance: str
    persona_hint: str
    project_id: str
    status: str
    route: str
    request_id: str
    fingerprint: str
    owner_token: str
    was_idempotent_hit: bool


def _db_path_for(workspace_root: str | Path) -> Path:
    from partner.index.job_repository import init as _init_jobs
    repo = _init_jobs(workspace_root)
    return Path(repo.db_path)


def _verify_identity(*, workspace_root, instance, recipient_ref) -> dict:
    if not recipient_ref:
        return {"instance_id": instance, "user_ref": None,
                "bot_id": None, "sender_openid": ""}
    from partner.identity.binding import verify_recipient
    return verify_recipient(str(workspace_root), instance, recipient_ref)


def _authorise_subject(*, subject_allowed, instance) -> None:
    if not subject_allowed:
        raise UnauthorisedInstanceError("subject has no allowed_instances")
    if instance not in subject_allowed:
        raise UnauthorisedInstanceError(
            f"subject is not authorised for instance {instance!r}"
        )


def _channel_for(reply_to: str) -> str:
    return "qq" if reply_to in {"qq", "both"} else "web"


def _allocate_job_id() -> str:
    """Stable, content-unique job id usable by both reservation
    table and jobs.db (so reservation ↔ Job can be reconciled).
    """
    return "job_" + uuid.uuid4().hex[:16]


def orchestrate_submit(
    *,
    workspace_root: str | Path,
    text: str,
    channel: str,
    sender_id: str,
    sender_name: str,
    persona_hint: str,
    project_id: str = "",
    mode: str = "",
    scope: str = "",
    execution_constraints: dict | None = None,
    attachments: list[dict] | None = None,
    report_policy: str = "milestone",
    request_id: str | None = None,
    recipient_ref: str | None = None,
    subject_allowed_instances: list[str] | None = None,
    subject_id: str = "",
    attachments_signature: list[dict] | None = None,
) -> SubmissionResult:
    from partner.identity.partners import resolve_partner
    try:
        instance = resolve_partner(persona_hint)
    except ValueError:
        raise ValueError(
            f"persona_hint must be a Partner (01..05 or readable name); got {persona_hint!r}"
        )

    binding = _verify_identity(workspace_root=workspace_root,
                                instance=instance,
                                recipient_ref=recipient_ref)
    real_sender_id = binding.get("sender_openid") or sender_id

    if subject_allowed_instances is not None:
        _authorise_subject(subject_allowed=subject_allowed_instances,
                            instance=instance)

    fp = compute_fingerprint(
        instance=instance, message=text, project_id=project_id,
        mode=mode, scope=scope, sender_id=real_sender_id,
        reply_to=channel, recipient_ref=recipient_ref,
        attachments=attachments_signature,
        execution_constraints=dict(execution_constraints or {}),
    )

    # ---------- direct_answer path ----------
    if not request_id:
        # Application layer may accept the message without producing a
        # Job (e.g. it routes to direct_answer).  We submit through the
        # service and return whatever the real Submission says.
        sub = _direct_submit(
            workspace_root=workspace_root, text=text,
            channel=channel, sender_id=real_sender_id,
            sender_name=sender_name, persona_hint=instance,
            project_id=project_id, mode=mode, scope=scope,
            execution_constraints=execution_constraints,
            attachments=attachments, report_policy=report_policy,
            fingerprint=fp,
        )
        # Direct answers may legitimately return accepted=True with
        # job_id="" — that is NOT a failure.
        return to_submission_result(
            job_id=sub.job_id,
            project_id=sub.project_id,
            assigned_instance=sub.assigned_instance or instance,
            status=sub.status or "direct_answer",
            route=sub.route or "direct_answer",
            message=sub.message,
            message_id=sub.message_id,
            request_id=request_id or "",
            fingerprint=fp,
            owner_token="",
            persona_hint=instance,
            was_idempotent_hit=False,
        )

    # ---------- idempotent path ----------
    db_path = str(_db_path_for(workspace_root))
    try:
        reap_expired(db_path)
    except Exception:
        pass

    try:
        reservation = reserve(
            db_path=db_path, request_id=request_id,
            workspace_root=str(workspace_root),
            subject_id=subject_id or real_sender_id,
            fingerprint=fp, instance=instance,
            persona_hint=instance, ttl_seconds=600,
        )
    except IdempotencyConflict:
        raise

    result = reservation["result"]
    owner_token = reservation["owner_token"]
    preallocated_job_id = reservation.get("preallocated_job_id", "")

    if result == "submitted":
        return _replay_submitted(
            workspace_root=workspace_root,
            reservation=reservation,
            fingerprint=fp,
            persona_hint=instance,
            project_id=project_id,
        )

    if result == "in_progress":
        # Request-recovery state machine (round 6): an active owner
        # yields a queryable in-progress state; a dead owner is
        # recovered by re-acquiring fenced ownership and either linking
        # the already-created Job (by pre-allocated id) or driving a
        # fresh Job — never a duplicate.
        r_state = reservation.get("state", "")
        r_subject = subject_id or real_sender_id
        if r_state == "submitted":
            return _replay_submitted(
                workspace_root=workspace_root, reservation=reservation,
                fingerprint=fp, persona_hint=instance, project_id=project_id,
            )
        try:
            reacq = reacquire(
                db_path=db_path, request_id=request_id,
                workspace_root=str(workspace_root), subject_id=r_subject,
                fingerprint=fp, instance=instance, persona_hint=instance,
            )
        except IdempotencyScopeError:
            raise _IdempotencyInProgress(
                f"request_id={request_id!r} is still owned "
                f"(state={r_state!r}, owner_token={owner_token[:12]}...); "
                f"job_id={preallocated_job_id or 'pending'}"
            )
        if reacq.get("result") == "submitted":
            return _replay_submitted(
                workspace_root=workspace_root, reservation=reacq,
                fingerprint=fp, persona_hint=instance, project_id=project_id,
            )
        new_owner = reacq["owner_token"]
        # Owner was dead and we re-acquired.  Check whether a Job was
        # already created under the pre-allocated id (crash between Job
        # insert and reservation.submitted write-back).
        existing_job = None
        if preallocated_job_id:
            try:
                from partner.index.job_repository import init as _init_jobs
                repo = _init_jobs(workspace_root)
                existing_job = repo.get_record(preallocated_job_id)
            except Exception:
                existing_job = None
        if existing_job:
            try:
                mark_state(
                    db_path=db_path, request_id=request_id,
                    workspace_root=str(workspace_root),
                    subject_id=r_subject, owner_token=new_owner,
                    new_state="submitted", job_id=preallocated_job_id,
                    assigned_instance=instance,
                )
            except NotYetOwned:
                raise _IdempotencyInProgress(
                    f"lost ownership while linking recovered job "
                    f"{preallocated_job_id}"
                )
            return to_submission_result(
                job_id=preallocated_job_id,
                project_id=project_id,
                assigned_instance=instance,
                status=str(existing_job.get("status") or "queued"),
                route="recovered_existing_job",
                message="",
                request_id=request_id,
                fingerprint=fp,
                owner_token=new_owner,
                persona_hint=instance,
                was_idempotent_hit=True,
            )
        # No Job yet: drive a fresh one under re-acquired ownership.
        try:
            sub = _execute_job(
                workspace_root=workspace_root,
                text=text, channel=channel,
                sender_id=real_sender_id, sender_name=sender_name,
                persona_hint=instance, project_id=project_id, mode=mode,
                scope=scope, execution_constraints=execution_constraints,
                attachments=attachments, report_policy=report_policy,
                fingerprint=fp,
                preallocated_job_id=preallocated_job_id,
            )
        except Exception:
            try:
                mark_state(
                    db_path=db_path, request_id=request_id,
                    workspace_root=str(workspace_root),
                    subject_id=r_subject, owner_token=new_owner,
                    new_state="failed",
                )
            except Exception:
                pass
            raise
        try:
            mark_state(
                db_path=db_path, request_id=request_id,
                workspace_root=str(workspace_root),
                subject_id=r_subject, owner_token=new_owner,
                new_state="submitted", job_id=sub.job_id,
                assigned_instance=sub.assigned_instance or instance,
            )
        except NotYetOwned:
            raise _IdempotencyInProgress(
                f"ownership lost during recovered submit; job_id={sub.job_id}"
            )
        return to_submission_result(
            job_id=sub.job_id,
            project_id=sub.project_id or project_id,
            assigned_instance=sub.assigned_instance or instance,
            status=sub.status or "queued",
            route=sub.route or "recovered",
            message=sub.message,
            message_id=sub.message_id,
            request_id=request_id,
            fingerprint=fp,
            owner_token=new_owner,
            persona_hint=instance,
            was_idempotent_hit=True,
        )

    if result != "created":
        raise RuntimeError(f"unexpected reserve() result: {result!r}")

    # We own the slot.  Transition to intent_pending.
    try:
        mark_state(
            db_path=db_path, request_id=request_id,
            workspace_root=str(workspace_root),
            subject_id=subject_id or real_sender_id,
            owner_token=owner_token, new_state="intent_pending",
        )
    except Exception:
        try:
            mark_state(
                db_path=db_path, request_id=request_id,
                workspace_root=str(workspace_root),
                subject_id=subject_id or real_sender_id,
                owner_token=owner_token, new_state="failed",
            )
        except Exception:
            pass
        raise

    # Pre-allocated job id; submit using that exact id so the
    # reservation ↔ Job relationship is durable from the moment
    # the Job row exists.
    try:
        sub = _execute_job(
            workspace_root=workspace_root,
            text=text, channel=channel,
            sender_id=real_sender_id, sender_name=sender_name,
            persona_hint=instance, project_id=project_id, mode=mode,
            scope=scope, execution_constraints=execution_constraints,
            attachments=attachments, report_policy=report_policy,
            fingerprint=fp,
            preallocated_job_id=preallocated_job_id,
        )
    except Exception:
        try:
            mark_state(
                db_path=db_path, request_id=request_id,
                workspace_root=str(workspace_root),
                subject_id=subject_id or real_sender_id,
                owner_token=owner_token, new_state="failed",
            )
        except Exception:
            pass
        raise

    try:
        mark_state(
            db_path=db_path, request_id=request_id,
            workspace_root=str(workspace_root),
            subject_id=subject_id or real_sender_id,
            owner_token=owner_token, new_state="submitted",
            job_id=sub.job_id,
            assigned_instance=sub.assigned_instance or instance,
        )
    except NotYetOwned:
        raise _IdempotencyInProgress(
            f"reservation ownership lost during intent flow; "
            f"job_id={sub.job_id} created but not linked"
        )

    return to_submission_result(
        job_id=sub.job_id,
        project_id=sub.project_id or project_id,
        assigned_instance=sub.assigned_instance or instance,
        status=sub.status or "queued",
        route=sub.route or "",
        message=sub.message,
        message_id=sub.message_id,
        request_id=request_id,
        fingerprint=fp,
        owner_token=owner_token,
        persona_hint=instance,
        was_idempotent_hit=False,
    )


def _replay_submitted(*, workspace_root, reservation, fingerprint,
                       persona_hint, project_id) -> SubmissionResult:
    job_id = reservation.get("job_id") or ""
    status = "queued"
    if job_id:
        try:
            from partner.index.job_repository import init as _init_jobs
            repo = _init_jobs(workspace_root)
            record = repo.get_record(job_id)
            if record:
                status = record.get("status") or "queued"
        except Exception:
            pass
    return to_submission_result(
        job_id=str(job_id),
        project_id=str(reservation.get("project_id") or project_id or ""),
        assigned_instance=str(reservation.get("assigned_instance") or persona_hint),
        status=str(status),
        route="idempotent_replay",
        request_id=str(reservation["request_id"]),
        fingerprint=fingerprint,
        owner_token=str(reservation.get("owner_token") or ""),
        persona_hint=str(persona_hint),
        was_idempotent_hit=True,
    )


def _direct_submit(*, workspace_root, text, channel, sender_id, sender_name,
                    persona_hint, project_id, mode, scope,
                    execution_constraints, attachments, report_policy,
                    fingerprint, preallocated_job_id="") -> "Submission":
    from partner.application.service import PartnerApplicationService
    svc = PartnerApplicationService(workspace_root)
    sub = svc.submit(
        text=text, channel=channel, sender_id=sender_id,
        sender_name=sender_name, persona_hint=persona_hint,
        project_id=project_id, attachments=attachments or (),
        report_policy=report_policy,
        execution_constraints=execution_constraints,
        mode=mode, scope=scope,
        preallocated_job_id=preallocated_job_id,
    )
    if not sub.accepted:
        raise RuntimeError(
            f"submission rejected by application service: {sub.message}"
        )
    # Direct answers may legitimately return job_id="" — that is
    # allowed (e.g. mode="direct_answer" routes to a one-shot reply).
    return sub


def _execute_job(*, workspace_root, text, channel, sender_id, sender_name,
                  persona_hint, project_id, mode, scope,
                  execution_constraints, attachments, report_policy,
                  fingerprint, preallocated_job_id="") -> "Submission":
    """Wrapper around ``PartnerApplicationService.submit`` for the
    idempotent path.  Returns the real Submission dataclass."""
    return _direct_submit(
        workspace_root=workspace_root, text=text, channel=channel,
        sender_id=sender_id, sender_name=sender_name,
        persona_hint=persona_hint, project_id=project_id,
        mode=mode, scope=scope, execution_constraints=execution_constraints,
        attachments=attachments, report_policy=report_policy,
        fingerprint=fingerprint,
        preallocated_job_id=preallocated_job_id,
    )


class _IdempotencyInProgress(IdempotencyScopeError):
    """Same fingerprint, reservation still in progress (no Job yet)."""


__all__ = [
    "SubmissionResult", "to_submission_result",
    "IdempotencyConflict", "IdempotencyScopeError",
    "NotYetOwned", "UnauthorisedInstanceError",
    "_IdempotencyInProgress",
    "RESERVATION_STATES",
    "orchestrate_submit",
    "compute_fingerprint", "canonical_payload",
]
