"""ACE (Agentic Context Engineering) adapter wired to EventMemory (M2).

This is **not** a wrapper around the upstream ACE package.  It is the
shape of an ACE entry plus the producer / consumer wiring into
Partner's existing append-only ``EventMemory``.

* **Producer:** ``append_to_memory`` delegates to
  ``EventMemory.append_semantic('lesson', ...)``.  This is the single
  source of truth for the JSONL row; no experimental parallel path is
  written.  Record-id is generated by EventMemory; ACE entry_id is the
  same as the EventMemory record_id (we pass it explicitly).
* **Consumer:** ``mark_usage`` delegates to
  ``EventMemory.record_usage`` so the usage_outcomes.jsonl row carries
  the same status taxonomy as the rest of the system.
* **Supersede / retire:** we expose a thin helper that appends a
  ``revoked`` row to the same store; the recall filter then hides it.

This adapter never speaks to the LLM; it is invoked by the events
that own memory production / consumption (``memory.observe``,
``memory.recall``, ``memory.consolidate``).

State honesty: ``static_implemented``.
"""
from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field, asdict, replace
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ACEEntry:
    entry_id: str
    strategy_id: str
    scope: str
    content: str
    helpful: int = 0
    harmful: int = 0
    superseded_by: str | None = None
    schema_version: str = "ace.entry/v1"
    recorded_at: str = field(default_factory=lambda: time.strftime("%Y-%m-%dT%H:%M:%S%z"))


def make_entry(*, strategy_id: str, scope: str, content: str) -> ACEEntry:
    if not strategy_id:
        raise ValueError("strategy_id must be non-empty")
    if not scope:
        raise ValueError("scope must be non-empty")
    return ACEEntry(
        entry_id="ace_" + uuid.uuid4().hex[:12],
        strategy_id=strategy_id, scope=scope, content=content,
    )


def update_feedback(entry: ACEEntry, *, helpful_delta: int = 0,
                    harmful_delta: int = 0) -> ACEEntry:
    return replace(entry, helpful=entry.helpful + helpful_delta,
                    harmful=entry.harmful + harmful_delta)


def retire(entry: ACEEntry, *, superseded_by: str) -> ACEEntry:
    if not superseded_by:
        raise ValueError("superseded_by must be non-empty")
    return replace(entry, superseded_by=superseded_by)


def to_jsonl_line(entry: ACEEntry) -> str:
    import json
    return json.dumps(asdict(entry), ensure_ascii=False, sort_keys=True)


def append_to_memory(entry: ACEEntry, *, workspace_root: str | Path) -> str:
    """Append ``entry`` through EventMemory so schema and lock are
    consistent with the rest of Partner.

    Returns the absolute path of the lessons.jsonl file.
    """
    root = Path(workspace_root).expanduser().resolve()
    from partner.memory.event_memory import EventMemory
    em = EventMemory(root)
    return em.append_semantic("lesson", {
        "record_id": entry.entry_id,
        "strategy_id": entry.strategy_id,
        "scope": entry.scope,
        "content": entry.content,
        "helpful": entry.helpful,
        "harmful": entry.harmful,
        "superseded_by": entry.superseded_by,
        "schema_version": entry.schema_version,
        "recorded_at": entry.recorded_at,
    })


def mark_usage(*, workspace_root: str | Path, entry_id: str,
                event_id: str, flow_id: str, effect: dict,
                status: str = "referenced") -> str:
    """Mark a usage event for ``entry_id`` via EventMemory.

    Status taxonomy matches ``EventMemory.record_usage``:
    ``referenced`` / ``applied`` / ``rejected``.  Raises on invalid
    status so callers cannot silently corrupt the usage stream.
    """
    root = Path(workspace_root).expanduser().resolve()
    from partner.memory.event_memory import EventMemory
    em = EventMemory(root)
    em.record_usage(event_id=event_id, flow_id=flow_id,
                     memory_ids=[entry_id], effect=effect, status=status)
    return str(root / "share" / "mind" / "memory" / "usage.jsonl")


__all__ = [
    "ACEEntry", "make_entry", "update_feedback", "retire",
    "to_jsonl_line", "append_to_memory", "mark_usage",
]
