"""Pattern Improver — generates concrete, executable improvement plans from gaps.

This module takes the gaps identified by PatternComparator and produces
specific, line-level improvement plans with real file paths and code diffs.

All code is generated by LLM — no hardcoded templates or preset patterns.

Each improvement plan is structured such that it could, in principle,
be auto-applied by the Implementation module.

Output format:
    {
        "target_file": "partner/desktop_gui/modern/Sidebar.py",
        "change_type": "modify" | "new_file" | "new_function" | "new_class",
        "description": "Add collapse/expand toggle to the sidebar",
        "code_diff": "+ def toggle_collapse(self): ...",
        "expected_impact": "User can collapse sidebar for more chat space",
        "risk_level": "low" | "medium" | "high",
        "estimated_effort": "30min" | "1h" | "2h" | "4h+",
        "dependencies": [],
    }

Usage:
    from partner.evolution.pattern_improver import PatternImprover

    plans = PatternImprover.generate_improvements(gaps)
    for plan in plans:
        print(f"  {plan['target_file']}: {plan['description']}")
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import re
from pathlib import Path
from typing import Any

from .code_knowledge import (
    PARTNER_GUI_ROOT,
    CodeKnowledge,
    ImprovementPlan,
)

logger = logging.getLogger(__name__)

# ── Partner GUI file structure ────────────────────────────────────────────────

PARTNER_GUI_DIR = Path("/mnt/e/work/partner/shells/frontend/desktop_gui/modern")

KNOWN_PARTNER_FILES: dict[str, str] = {
    "main_window.py": "主窗口 — 包含 MainWindow、Sidebar、ContentArea",
    "widgets.py": "可复用组件 — ChatBubble、EventCard、AccentButton、StatusCard",
    "pages/chat.py": "对话页面 — 聊天界面、消息列表、输入框",
    "pages/instances.py": "实例管理页面 — 实例列表、状态显示",
    "pages/settings.py": "设置页面 — 应用配置选项",
    "styles.py": "样式表 — QSS 样式定义和主题",
    "app.py": "应用入口 — QApplication 初始化和启动",
}


# ═══════════════════════════════════════════════════════════════════════════════
# Core Module
# ═══════════════════════════════════════════════════════════════════════════════


class PatternImprover:
    """Generate concrete, executable improvement plans from gap analysis.

    All code generation is done via LLM (HermesAdapter). No hardcoded
    templates or preset pattern matching.
    """

    _plan_counter: int = 0

    # ── Public API ─────────────────────────────────────────────────────────

    @classmethod
    async def generate_improvements(
        cls,
        gaps: list[dict[str, Any]],
        partner_gui_root: str | Path | None = None,
        progress_callback=None,
    ) -> list[dict[str, Any]]:
        """Convert gap entries into concrete, executable improvement plans.

        For 2+ gaps, uses a SINGLE batched LLM call instead of N sequential
        calls.  This reduces the 12-minute synchronous block to ~30 seconds.

        All HTTP calls are dispatched via asyncio.to_thread() so the event loop
        remains free for progress callbacks and message processing.

        Each plan specifies:
        - Exact file path to modify
        - What kind of change (modify, new file, new class)
        - The specific code diff/snippet
        - Expected impact
        - Risk level and estimated effort

        Args:
            gaps: List of gap dicts from PatternComparator.compare().
            partner_gui_root: Override Partner GUI root path.
            progress_callback: Optional callable(msg) for progress reporting.

        Returns:
            List of structured improvement plan dicts.
        """
        cls._plan_counter = 0
        gui_root = Path(partner_gui_root) if partner_gui_root else PARTNER_GUI_ROOT

        if len(gaps) >= 2:
            # ── Batch mode: single LLM call for all gaps ──
            if progress_callback:
                await progress_callback(f"💡 批量生成 {len(gaps)} 个改进方案（一次 LLM 调用，预计 30-60 秒）...")
            plans = await cls._generate_plans_batch(gaps, gui_root)
        else:
            # ── Sequential mode: one LLM call per gap (1 gap only) ──
            plans = []
            for idx, gap in enumerate(gaps):
                plan = await cls._gap_to_plan(gap, gui_root)
                if plan:
                    plans.append(plan)
                if progress_callback and (idx + 1) % 5 == 0:
                    await progress_callback(
                        f"💡 正在生成改进方案... ({idx + 1}/{len(gaps)})"
                    )

        # Sort by risk level (high priority first)
        risk_order = {"high": 0, "medium": 1, "low": 2}
        plans.sort(key=lambda p: risk_order.get(p.get("risk_level", "low"), 99))

        logger.info(
            "Generated %d improvement plans (high=%d, med=%d, low=%d)",
            len(plans),
            sum(1 for p in plans if p.get("risk_level") == "high"),
            sum(1 for p in plans if p.get("risk_level") == "medium"),
            sum(1 for p in plans if p.get("risk_level") == "low"),
        )

        return plans

    @classmethod
    async def generate_improvement_plans(
        cls,
        gaps: list[dict[str, Any]],
    ) -> list[ImprovementPlan]:
        """Generate ImprovementPlan objects (compatible with SelfEvolveEngine).

        Uses the existing ImprovementPlan dataclass so these plans can flow
        into the existing Implementation module.

        Args:
            gaps: List of gap dicts from PatternComparator.compare().

        Returns:
            List of ImprovementPlan objects.
        """
        cls._plan_counter = 0
        plans: list[ImprovementPlan] = []

        for gap in gaps:
            plan_dict = await cls._gap_to_plan(gap, PARTNER_GUI_ROOT)
            if not plan_dict:
                continue

            # Determine change_type and risk for ImprovementPlan format
            risk = plan_dict.get("risk_level", "medium")
            change_type = plan_dict.get("change_type", "modify_function")
            if change_type == "new_file":
                change_type = "add_feature"
            elif change_type == "new_class":
                change_type = "add_feature"

            plans.append(ImprovementPlan(
                id=f"plan_im{cls._plan_counter:03d}",
                target_module=plan_dict["target_file"],
                change_type=change_type,
                function_name="",
                new_code=plan_dict.get("code_diff", ""),
                description=plan_dict["description"],
                risk_level=risk,
            ))

        logger.info(
            "Generated %d ImprovementPlan objects from %d gaps",
            len(plans), len(gaps),
        )
        return plans

    # ── Gap → Plan conversion ──────────────────────────────────────────────

    @classmethod
    async def _gap_to_plan(
        cls, gap: dict[str, Any], gui_root: Path
    ) -> dict[str, Any] | None:
        """Convert a single gap dict into a concrete improvement plan."""
        cls._plan_counter += 1

        category = gap.get("category", "")
        pattern_name = gap.get("external_pattern", "")
        priority = gap.get("priority", "medium")

        # Determine which Partner file to modify
        target_file, change_type = cls._determine_target(category, pattern_name)

        # Generate specific code suggestion via LLM
        code_diff = await cls._generate_code(pattern_name, category, change_type, target_file)

        # Build description
        description = (
            f"[{category}] {pattern_name}："
            f"{gap.get('partner_status', '')}。"
            f"{gap.get('suggestion', '')}"
        )

        # Assess risk and effort
        risk_level, estimated_effort = cls._assess_risk_and_effort(
            category, change_type, priority,
        )

        # Determine expected impact
        expected_impact = cls._determine_impact(category, pattern_name)

        # Check for dependencies
        dependencies = cls._determine_dependencies(category, pattern_name, target_file)

        plan: dict[str, Any] = {
            "plan_id": f"plan_{cls._plan_counter:03d}",
            "target_file": target_file,
            "change_type": change_type,
            "description": description,
            "code_diff": code_diff,
            "expected_impact": expected_impact,
            "risk_level": risk_level,
            "estimated_effort": estimated_effort,
            "dependencies": dependencies,
            "category": category,
            "gap_id": gap.get("gap_id", ""),
            "external_source": gap.get("external_source", ""),
            "external_file": gap.get("external_file", ""),
        }

        return plan

    # ── Target File Resolution ─────────────────────────────────────────────

    @classmethod
    def _determine_target(
        cls, category: str, pattern_name: str
    ) -> tuple[str, str]:
        """Determine which Partner file to modify and what kind of change.

        Returns:
            Tuple of (relative_file_path, change_type).
        """
        if category == "布局":
            if "侧边栏" in pattern_name or "sidebar" in pattern_name.lower():
                return "shells/frontend/desktop_gui/modern/main_window.py", "modify"
            elif "导航" in pattern_name:
                return "shells/frontend/desktop_gui/modern/main_window.py", "modify"
            elif "网格" in pattern_name or "flex" in pattern_name.lower():
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "分割" in pattern_name or "split" in pattern_name.lower():
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            else:
                return "shells/frontend/desktop_gui/modern/main_window.py", "modify"

        elif category == "交互":
            if "键盘" in pattern_name or "快捷键" in pattern_name:
                return "shells/frontend/desktop_gui/modern/pages/chat.py", "modify"
            elif "拖拽" in pattern_name:
                return "shells/frontend/desktop_gui/modern/pages/chat.py", "modify"
            elif "悬停" in pattern_name or "hover" in pattern_name.lower():
                return "shells/frontend/desktop_gui/modern/widgets.py", "modify"
            elif "动画" in pattern_name or "过渡" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "modify"
            elif "展开" in pattern_name or "折叠" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "modify"
            else:
                return "shells/frontend/desktop_gui/modern/pages/chat.py", "modify"

        elif category == "组件":
            if "Toast" in pattern_name or "Notification" in pattern_name or "通知" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Avatar" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Badge" in pattern_name or "标签" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Tooltip" in pattern_name or "提示" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Progress" in pattern_name or "Spinner" in pattern_name or "加载" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Search" in pattern_name or "搜索" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Dropdown" in pattern_name or "Select" in pattern_name or "选择" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "Markdown" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"
            elif "ANSI" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_function"
            elif "暗色" in pattern_name or "主题" in pattern_name or "dark" in pattern_name.lower():
                return "shells/frontend/desktop_gui/modern/styles.py", "new_file"
            else:
                return "shells/frontend/desktop_gui/modern/widgets.py", "new_class"

        elif category == "样式":
            if "主题" in pattern_name or "theme" in pattern_name.lower():
                return "shells/frontend/desktop_gui/modern/styles.py", "new_file"
            elif "响应式" in pattern_name:
                return "shells/frontend/desktop_gui/modern/main_window.py", "modify"
            else:
                return "shells/frontend/desktop_gui/modern/styles.py", "modify"

        elif category == "架构":
            if "测试" in pattern_name:
                return "shells/frontend/desktop_gui/tests/", "new_file"
            elif "配置" in pattern_name or "设置" in pattern_name:
                return "shells/frontend/desktop_gui/modern/pages/settings.py", "modify"
            elif "组件化" in pattern_name:
                return "shells/frontend/desktop_gui/modern/widgets.py", "modify"
            else:
                return "shells/frontend/desktop_gui/modern/widgets.py", "modify"

        return "shells/frontend/desktop_gui/modern/widgets.py", "modify"

    # ── LLM Code Generation ────────────────────────────────────────────────

    @classmethod
    def _build_code_prompt(
        cls,
        pattern_name: str,
        category: str,
        change_type: str,
        target_file: str,
    ) -> str:
        """Build a prompt for the LLM to generate code for a specific improvement.

        Args:
            pattern_name: Name of the pattern to implement (e.g. "侧边栏折叠").
            category: Category (布局/交互/组件/样式/架构).
            change_type: Type of change (modify/new_class/new_file).
            target_file: Relative path to the target file.

        Returns:
            A prompt string for the LLM.
        """
        # Read existing file content for context
        project_root = Path("/mnt/e/work/partner")
        full_path = project_root / target_file
        existing_content = ""
        if full_path.exists():
            try:
                existing_content = full_path.read_text(encoding="utf-8")
                # Truncate to avoid overwhelming the LLM
                if len(existing_content) > 6000:
                    existing_content = existing_content[:6000] + "\n    ... (truncated)"
            except Exception:
                existing_content = ""

        prompt = f"""你是一个 Python 代码生成器。Partner 是一个基于 PySide6 的桌面应用。

当前需要改进的模块：{target_file}
改进需求类别：{category}
改进具体内容：{pattern_name}
修改类型：{change_type}

Partner 现有代码风格：
- 使用 PySide6.QtWidgets 和 PySide6.QtCore
- 类名使用 PascalCase，函数名使用 snake_case
- 类型注解使用 Python 3.10+ 语法
- 信号用 Signal() 定义，槽用 @Slot() 装饰器

目标文件现有内容（供参考上下文）：
```python
{existing_content if existing_content else "(新文件，暂无内容)"}
```

请生成完整的 Python 代码片段：
1. 如果是新增功能（new_class/new_function），包含完整的类或函数实现
2. 如果是修改现有功能（modify），包含修改后的完整函数/方法
3. 包含必要的 import 语句（只包含 Python 标准库和 PySide6 的 import）
4. 代码必须语法正确，可直接追加写入目标文件
5. 如果无法生成有意义的代码，返回空字符串

只输出 Python 代码，不要包含任何解释或 Markdown 标记。"""
        return prompt

    # ── API Key Resolution ────────────────────────────────────────────────

    @classmethod
    def _resolve_api_key(cls) -> str:
        """Resolve DeepSeek API key from env vars or Hermes config."""
        import os as _os
        key = _os.environ.get("DEEPSEEK_API_KEY", "")
        if key:
            return key
        try:
            cfg_path = _os.path.expanduser("~/.hermes/config.yaml")
            if _os.path.exists(cfg_path):
                with open(cfg_path) as _f:
                    for _line in _f:
                        if "api_key" in _line.lower() and "deepseek" in _line.lower():
                            key = _line.split(":", 1)[-1].strip().strip('"').strip("'")
                            if key:
                                return key
        except Exception:
            pass
        return _os.environ.get("OPENAI_API_KEY", "")

    # ── Code Generation ────────────────────────────────────────────────────

    @classmethod
    async def _generate_code(
        cls,
        pattern_name: str,
        category: str,
        change_type: str,
        target_file: str,
        workspace: str = "",
    ) -> str:
        """Generate concrete code for the improvement using LLM.

        Uses asyncio.to_thread() to avoid blocking the event loop during
        the synchronous urllib.request.urlopen() call.
        """
        prompt = cls._build_code_prompt(pattern_name, category, change_type, target_file)

        try:
            api_key = cls._resolve_api_key()
            if not api_key:
                logger.warning("[IMPROVER] No API key for code generation")
                return ""

            import urllib.request as _ur

            def _do_sync_llm_call(payload_bytes: bytes) -> str:
                """Synchronous HTTP call — runs in executor thread."""
                req = _ur.Request(
                    "https://api.deepseek.com/chat/completions",
                    data=payload_bytes,
                    headers={
                        "Content-Type": "application/json",
                        "Authorization": f"Bearer {api_key}",
                    },
                )
                resp = _ur.urlopen(req, timeout=30)
                resp_data = json.loads(resp.read())
                return resp_data["choices"][0]["message"]["content"].strip()

            payload = json.dumps({
                "model": "deepseek-chat",
                "messages": [
                    {"role": "system", "content": "You are a Python code generator. Output ONLY Python code. No explanations. No markdown."},
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": 2000,
                "temperature": 0.3,
            }).encode()

            code = await asyncio.to_thread(_do_sync_llm_call, payload)

            if not code:
                logger.warning("[IMPROVER] LLM returned empty for %s (%s)", pattern_name, category)
                return ""

            # Strip markdown code fences if present
            code = code.strip()
            if code.startswith("```python"):
                code = code[len("```python"):]
            if code.startswith("```"):
                code = code[len("```"):]
            if code.endswith("```"):
                code = code[:-len("```")]
            code = code.strip()

            # Basic validation: must be non-empty Python
            if not code:
                return ""

            # Try to compile to verify syntax
            try:
                compile(code, "<generated>", "exec")
            except SyntaxError as _se:
                logger.warning(
                    "[IMPROVER] LLM generated code with syntax error for %s: %s",
                    pattern_name, _se,
                )
                return ""

            logger.info(
                "[IMPROVER] LLM generated %d bytes of code for %s (%s)",
                len(code), pattern_name, category,
            )
            return code

        except Exception as e:
            logger.warning(
                "[IMPROVER] LLM code generation failed for %s (%s): %s",
                pattern_name, category, e,
            )
            return ""

    # ── Batched Code Generation ─────────────────────────────────────────

    @classmethod
    async def _generate_plans_batch(
        cls,
        gaps: list[dict[str, Any]],
        gui_root: Path,
        progress_callback=None,
    ) -> list[dict[str, Any]]:
        """Generate improvement plans for ALL gaps in a single LLM call.

        Each gap specifies a target file and a pattern to implement.
        The LLM receives all gaps at once and returns code for each one,
        dramatically reducing latency compared to N sequential calls.

        HTTP call is dispatched via asyncio.to_thread() so the event loop
        stays free for progress updates.
        """
        if not gaps:
            return []

        # Collect unique target files and read their contents
        project_root = Path("/mnt/e/work/partner")
        file_contexts: dict[str, str] = {}
        gap_entries: list[dict] = []
        for gap in gaps:
            category = gap.get("category", "")
            pattern_name = gap.get("external_pattern", "")
            priority = gap.get("priority", "medium")
            change_type = "modify"
            target_file = "shells/frontend/desktop_gui/modern/widgets.py"

            # Determine target file using existing logic
            target_file, change_type = cls._determine_target(category, pattern_name)

            if target_file not in file_contexts:
                full_path = project_root / target_file
                ctx = ""
                if full_path.exists():
                    try:
                        ctx = full_path.read_text(encoding="utf-8")
                        if len(ctx) > 4000:
                            ctx = ctx[:4000] + "\n    ... (truncated)"
                    except Exception:
                        ctx = ""
                file_contexts[target_file] = ctx if ctx else "(新文件，暂无内容)"

            risk, effort = cls._assess_risk_and_effort(category, change_type, priority)
            impact = cls._determine_impact(category, pattern_name)
            deps = cls._determine_dependencies(category, pattern_name, target_file)

            gap_entries.append({
                "category": category,
                "pattern": pattern_name,
                "change_type": change_type,
                "target_file": target_file,
                "priority": priority,
                "risk_level": risk,
                "estimated_effort": effort,
                "expected_impact": impact,
                "dependencies": deps,
                "gap_id": gap.get("gap_id", ""),
                "external_source": gap.get("external_source", ""),
                "external_file": gap.get("external_file", ""),
                "partner_status": gap.get("partner_status", ""),
                "suggestion": gap.get("suggestion", ""),
            })

        # Build the batched prompt
        gaps_json = json.dumps(
            [{"target": g["target_file"], "category": g["category"],
              "pattern": g["pattern"], "change": g["change_type"]}
             for g in gap_entries], ensure_ascii=False, indent=2)

        file_section = ""
        for fpath, content in sorted(file_contexts.items()):
            file_section += f"\n### {fpath}\n```python\n{content}\n```\n"

        prompt = f"""你是一个 Python 代码生成器。Partner 是一个基于 PySide6 的桌面应用。

需要为以下 {len(gap_entries)} 个改进需求分别生成代码。
每个需求指定了目标文件和修改类型。请为每个需求输出完整的 Python 代码。

改进需求列表（JSON）：
{gaps_json}

目标文件现有内容：
{file_section}

Partner 代码风格：
- 使用 PySide6.QtWidgets 和 PySide6.QtCore
- 类名 PascalCase，函数名 snake_case
- 类型注解 Python 3.10+
- 信号 Signal()，槽 @Slot()
- 不要输出 from __future__ import annotations

请按以下 JSON 格式输出（只输出 JSON，不要 Markdown）：
{{"plans": [
  {{"pattern": "模式名称", "code": "Python代码"}},
  ...
]}}

每个 code 字段包含完整的 Python 代码片段，可独立追加到对应目标文件。
如果某个需求无法生成有意义的代码，code 设为空字符串。"""

        # ── Call LLM once via async to_thread() ──
        api_key = cls._resolve_api_key()
        if not api_key:
            logger.warning("[IMPROVER] No API key for batch code generation")
            return []

        import urllib.request as _ur

        def _do_batch_llm_call(payload_bytes: bytes) -> str:
            """Synchronous HTTP request — runs in executor thread."""
            req = _ur.Request(
                "https://api.deepseek.com/chat/completions",
                data=payload_bytes,
                headers={
                    "Content-Type": "application/json",
                    "Authorization": f"Bearer {api_key}",
                },
            )
            resp = _ur.urlopen(req, timeout=120)
            data = json.loads(resp.read())
            return data["choices"][0]["message"]["content"].strip()

        try:
            if progress_callback:
                await progress_callback("⏳ 正在等待 LLM 生成代码（预计 30-60 秒）...")

            payload = json.dumps({
                "model": "deepseek-chat",
                "messages": [
                    {"role": "system", "content": "You are a Python code generator. Output ONLY valid JSON. No explanations."},
                    {"role": "user", "content": prompt},
                ],
                "max_tokens": 32000,
                "temperature": 0.3,
            }).encode()

            raw = await asyncio.to_thread(_do_batch_llm_call, payload)

            if progress_callback:
                await progress_callback("📝 正在解析 LLM 返回的改进方案...")

            # Strip markdown fences
            if raw.startswith("```json"):
                raw = raw[7:]
            elif raw.startswith("```"):
                raw = raw[3:]
            if raw.endswith("```"):
                raw = raw[:-3]
            raw = raw.strip()

            result = json.loads(raw)
            plans_data = result.get("plans", []) if isinstance(result, dict) else result

            plans = []
            for i, entry in enumerate(gap_entries):
                cls._plan_counter += 1
                code = ""
                # Find matching plan by pattern name or index
                for pd in plans_data:
                    if isinstance(pd, dict):
                        if pd.get("pattern") == entry["pattern"]:
                            code = pd.get("code", "")
                            break
                else:
                    # Fallback: use index
                    if i < len(plans_data):
                        pd = plans_data[i]
                        if isinstance(pd, dict):
                            code = pd.get("code", "")
                        elif isinstance(pd, str):
                            code = pd

                # Validate: compile to check syntax
                if code and code.strip():
                    try:
                        compile(code.strip(), "<generated>", "exec")
                    except SyntaxError:
                        logger.warning("[IMPROVER] Batch LLM code has syntax error for %s: skipping", entry["pattern"])
                        code = ""

                plan = {
                    "plan_id": f"plan_{cls._plan_counter:03d}",
                    "target_file": entry["target_file"],
                    "change_type": entry["change_type"],
                    "description": (
                        f"[{entry['category']}] {entry['pattern']}："
                        f"{entry.get('partner_status', '')}。"
                        f"{entry.get('suggestion', '')}"
                    ),
                    "code_diff": code,
                    "expected_impact": entry["expected_impact"],
                    "risk_level": entry["risk_level"],
                    "estimated_effort": entry["estimated_effort"],
                    "dependencies": entry["dependencies"],
                    "category": entry["category"],
                    "gap_id": entry["gap_id"],
                    "external_source": entry.get("external_source", ""),
                    "external_file": entry.get("external_file", ""),
                }
                plans.append(plan)

            logger.info("[IMPROVER] Batch generated %d plans in 1 LLM call", len(plans))
            return plans

        except Exception as e:
            logger.warning("[IMPROVER] Batch LLM generation failed: %s", e)
            # Fallback: sequential per-gap generation
            logger.info("[IMPROVER] Falling back to sequential generation for %d gaps", len(gaps))
            if progress_callback:
                await progress_callback(f"⚠️ 批量生成失败，逐个生成 {len(gaps)} 个方案...")
            plans = []
            for idx, gap in enumerate(gaps):
                plan = await cls._gap_to_plan(gap, gui_root)
                if plan:
                    plans.append(plan)
                if progress_callback and (idx + 1) % 5 == 0:
                    await progress_callback(
                        f"💡 逐个生成改进方案... ({idx + 1}/{len(gaps)})"
                    )
            return plans

    # ── Risk / Effort Assessment ───────────────────────────────────────────

    @classmethod
    def _assess_risk_and_effort(
        cls, category: str, change_type: str, priority: str
    ) -> tuple[str, str]:
        """Assess risk level and estimated effort.

        Returns:
            Tuple of (risk_level, estimated_effort).
        """
        # New files are higher risk than modifications
        if change_type == "new_file":
            risk = "high"
            effort = "2h"
        elif change_type == "new_class":
            risk = "medium"
            effort = "1h"
        elif change_type == "modify":
            risk = "medium"
            effort = "30min"
        else:
            risk = "low"
            effort = "30min"

        # Adjust by priority
        if priority == "high":
            risk = risk  # keep as-is for high-priority gaps
        elif priority == "low":
            risk = "low"
            effort = "30min"

        return risk, effort

    @classmethod
    def _determine_impact(
        cls, category: str, pattern_name: str
    ) -> str:
        """Describe the expected user-facing impact of this improvement."""
        if category == "布局":
            if "侧边栏" in pattern_name:
                return "用户可折叠侧边栏，获得更多对话空间"
            elif "导航" in pattern_name:
                return "更便捷的页面导航和切换"
            elif "网格" in pattern_name:
                return "更灵活的内容布局排列"
            elif "分割" in pattern_name:
                return "可调整大小的面板布局，提升多任务体验"
            else:
                return "改善界面空间利用率和视觉效果"

        elif category == "交互":
            if "键盘" in pattern_name:
                return "支持键盘快捷键操作，提升效率"
            elif "拖拽" in pattern_name:
                return "支持拖拽操作（如文件上传、面板重排）"
            elif "悬停" in pattern_name:
                return "更丰富的鼠标悬停视觉反馈"
            elif "动画" in pattern_name:
                return "更流畅的界面切换和状态变化"
            elif "展开" in pattern_name:
                return "可折叠的详情区域，界面更简洁"
            else:
                return "提升界面交互体验"

        elif category == "组件":
            if "Toast" in pattern_name or "通知" in pattern_name:
                return "操作反馈即时可见，无需等待日志"
            elif "Avatar" in pattern_name:
                return "用户身份可视化，界面更个性化"
            elif "Badge" in pattern_name:
                return "未读消息、状态标记一目了然"
            elif "Tooltip" in pattern_name:
                return "鼠标悬停即可获得功能说明，降低学习成本"
            elif "Progress" in pattern_name:
                return "长时间操作有进度反馈，避免困惑"
            elif "Search" in pattern_name:
                return "支持快速搜索和过滤内容"
            elif "Markdown" in pattern_name:
                return "富文本消息渲染，阅读体验更好"
            elif "ANSI" in pattern_name:
                return "终端输出带颜色高亮，日志更易读"
            elif "暗色" in pattern_name or "主题" in pattern_name:
                return "用户可切换暗色/亮色主题，适配不同环境"
            else:
                return "新增 UI 组件，扩展界面功能"

        elif category == "样式":
            if "主题" in pattern_name:
                return "可切换主题，提升视觉一致性和用户体验"
            elif "响应式" in pattern_name:
                return "窗口大小变化时界面自适应布局"
            else:
                return "改善界面视觉效果"

        elif category == "架构":
            if "测试" in pattern_name:
                return "UI 自动化测试覆盖，防止回归"
            elif "配置" in pattern_name:
                return "用户可集中管理配置选项"
            elif "组件化" in pattern_name:
                return "代码更模块化，维护成本降低"
            else:
                return "改进代码架构质量"

        return "改善用户体验"

    @classmethod
    def _determine_dependencies(
        cls, category: str, pattern_name: str, target_file: str
    ) -> list[str]:
        """Determine what other changes are needed before this one."""
        deps: list[str] = []

        if "暗色" in pattern_name or "主题" in pattern_name:
            deps.append("创建 design_tokens.py 主题系统")
        if "键盘" in pattern_name:
            deps.append("确认 input widget 是自定义 QPlainTextEdit 子类")
        if "Toast" in pattern_name or "Notification" in pattern_name:
            deps.append("需要 design_tokens.py 中的颜色变量")

        return deps

    # ── Plan rendering ─────────────────────────────────────────────────────

    @classmethod
    def format_plan_human_readable(
        cls, plans: list[dict[str, Any]]
    ) -> str:
        """Format improvement plans as a human-readable text report."""
        lines: list[str] = []
        lines.append("=" * 60)
        lines.append("📋 代码学习改进方案")
        lines.append("=" * 60)

        risk_icons = {"high": "🔴", "medium": "🟡", "low": "🟢"}

        for i, plan in enumerate(plans, 1):
            lines.append("")
            lines.append(f"{'─' * 40}")
            lines.append(
                f"{risk_icons.get(plan.get('risk_level', 'low'), '⚪')} "
                f"方案 #{i}: {plan.get('description', '')[:100]}"
            )
            lines.append(f"  文件: {plan.get('target_file', '?')}")
            lines.append(f"  类型: {plan.get('change_type', 'modify')}")
            lines.append(f"  风险: {plan.get('risk_level', '?')} | "
                         f"预估: {plan.get('estimated_effort', '?')}")
            lines.append(f"  影响: {plan.get('expected_impact', '')}")

            deps = plan.get('dependencies', [])
            if deps:
                lines.append(f"  依赖: {', '.join(deps)}")

            code = plan.get('code_diff', '')
            if code:
                lines.append(f"  代码片段:")
                code_lines = code.strip().split("\n")
                for cl in code_lines[:8]:
                    lines.append(f"    {cl}")
                if len(code_lines) > 8:
                    lines.append(f"    ... ({len(code_lines)} 行)")

        lines.append("")
        lines.append("=" * 60)
        lines.append(f"共 {len(plans)} 个改进方案")
        lines.append("=" * 60)

        return "\n".join(lines)

    @classmethod
    def format_plan_json(
        cls, plans: list[dict[str, Any]]
    ) -> str:
        """Format improvement plans as a JSON string."""
        import json
        return json.dumps(
            plans,
            indent=2,
            ensure_ascii=False,
            default=str,
        )
