"""Verification — before/after benchmark comparison for Partner's self-evolution.

Part of the 5-step self-evolution cycle. Compares system performance on a
representative set of benchmark tasks *before* and *after* an improvement plan
is applied, then produces a verdict (effective / neutral / regressive).

The verification flow:

1. Run a set of representative benchmark tasks (3-5 tasks)
2. Record metrics *before* improvement (avg_time, success_rate, error_count)
3. Apply the improvement (signal the agent via desktop_inbox injection)
4. Re-run the same benchmark tasks
5. Record metrics *after* improvement
6. Compare and produce a verdict

Task execution uses the **desktop_inbox injection** method:

- Write the task description to ``<workspace>/state/desktop_inbox.jsonl``
- Poll ``<workspace>/state/qq_chat_history.jsonl`` for the agent's reply
- Timeout after 120 seconds
- Track start/end time and whether a reply was received

Usage::

    import asyncio

    async def main():
        result = await run_verification(
            plan_id="plan_001",
            benchmark_tasks=[
                "Run BLAST search on the provided sequence",
                "Parse the PDB file and extract residue contacts",
                "Convert the FASTA file to CSV format",
            ],
            workspace="/mnt/e/work/partner_workspace/instances/03",
        )
        print(generate_report(result))
        print("Verdict:", result.verdict)

    asyncio.run(main())
"""

from __future__ import annotations

import json
import logging
import os
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)

# ── Constants ──────────────────────────────────────────────────────────────────

_DEFAULT_TIMEOUT_S = 120  # seconds to wait for a single task reply
_POLL_INTERVAL_S = 0.5  # seconds between polls of qq_chat_history
_IMPROVEMENT_INJECT_WAIT_S = 5.0  # seconds to wait after injecting improvement

# Verdict thresholds
_TIME_IMPROVEMENT_THRESHOLD = 0.10  # 10% improvement in avg_time
_SUCCESS_RATE_DEGRADE_THRESHOLD = 0.10  # 10% drop in success_rate


# ═══════════════════════════════════════════════════════════════════════════════
# Dataclasses
# ═══════════════════════════════════════════════════════════════════════════════


@dataclass
class TaskMetrics:
    """Metrics collected from a single benchmark task execution.

    Attributes:
        task: The task description that was executed.
        avg_time: Average wall-clock time (seconds) to receive a reply.
            If no reply was received, this is the timeout duration.
        success_rate: Fraction (0.0–1.0) indicating whether the agent
            produced a substantive reply.  1.0 = success, 0.0 = failure.
        error_count: Number of errors encountered during execution
            (timeouts, empty replies, malformed responses).
        steps_completed: Number of processing steps observed (e.g. lines
            added to the chat history that reference this task).
    """

    task: str
    avg_time: float = 0.0
    success_rate: float = 0.0
    error_count: int = 0
    steps_completed: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dictionary."""
        return {
            "task": self.task,
            "avg_time": round(self.avg_time, 3),
            "success_rate": round(self.success_rate, 3),
            "error_count": self.error_count,
            "steps_completed": self.steps_completed,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> TaskMetrics:
        """Deserialize from a dictionary (inverse of :meth:`to_dict`)."""
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class VerificationResult:
    """Result of a complete before/after verification cycle.

    Attributes:
        plan_id: Identifier of the improvement plan being verified.
        before_metrics: List of :class:`TaskMetrics` collected *before*
            the improvement was applied.
        after_metrics: List of :class:`TaskMetrics` collected *after*
            the improvement was applied.
        verdict: One of ``"effective"``, ``"neutral"``, or ``"regressive"``.
        report: Human-readable verification report string, generated by
            :func:`generate_report`.
        summary_stats: Aggregated statistics for the before and after runs.
            Contains keys ``"before"`` and ``"after"``, each with ``avg_time``,
            ``success_rate``, and ``error_count`` averaged across tasks.
        improvements: Dictionary of deltas (after - before) for each metric,
            e.g. ``{"avg_time_delta": -2.5, "success_rate_delta": 0.05}``.
    """

    plan_id: str
    before_metrics: list[TaskMetrics] = field(default_factory=list)
    after_metrics: list[TaskMetrics] = field(default_factory=list)
    verdict: str = "unknown"
    report: str = ""
    summary_stats: dict[str, dict[str, float]] = field(default_factory=dict)
    improvements: dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dictionary."""
        return {
            "plan_id": self.plan_id,
            "before_metrics": [m.to_dict() for m in self.before_metrics],
            "after_metrics": [m.to_dict() for m in self.after_metrics],
            "verdict": self.verdict,
            "report": self.report,
            "summary_stats": self.summary_stats,
            "improvements": self.improvements,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> VerificationResult:
        """Deserialize from a dictionary (inverse of :meth:`to_dict`)."""
        return cls(
            plan_id=data.get("plan_id", ""),
            before_metrics=[TaskMetrics.from_dict(m) for m in data.get("before_metrics", [])],
            after_metrics=[TaskMetrics.from_dict(m) for m in data.get("after_metrics", [])],
            verdict=data.get("verdict", "unknown"),
            report=data.get("report", ""),
            summary_stats=data.get("summary_stats", {}),
            improvements=data.get("improvements", {}),
        )


# ═══════════════════════════════════════════════════════════════════════════════
# Desktop Inbox Injection Helpers
# ═══════════════════════════════════════════════════════════════════════════════


def _inbox_path(workspace: str) -> str:
    """Return the absolute path to the desktop_inbox.jsonl file."""
    return os.path.join(workspace, "state", "desktop_inbox.jsonl")


def _chat_history_path(workspace: str) -> str:
    """Return the absolute path to the qq_chat_history.jsonl file."""
    return os.path.join(workspace, "state", "qq_chat_history.jsonl")


def _now_iso() -> str:
    """Return the current UTC timestamp as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


def _inject_task(workspace: str, task_description: str) -> str:
    """Inject a task into the desktop_inbox.jsonl and return the message_id.

    The message is written as a JSONL line with ``role: user`` and
    ``source: desktop_gui``, mimicking a real user message from the GUI.

    Args:
        workspace: Absolute path to the Partner workspace.
        task_description: The task to submit to the agent.

    Returns:
        The generated message_id (UUID string) that can be used to
        identify replies in the chat history.
    """
    message_id = f"benchmark_{uuid.uuid4().hex[:12]}"
    entry = {
        "role": "user",
        "content": task_description.strip(),
        "timestamp": _now_iso(),
        "source": "desktop_gui",
        "message_id": message_id,
        "sender_id": "verification",
        "sender_name": "Verification Module",
    }
    path = _inbox_path(workspace)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    logger.debug("[VERIFY] Injected task: message_id=%s | task=%.60s", message_id, task_description)
    return message_id


def _poll_for_reply(
    workspace: str,
    message_id: str,
    *,
    timeout: int = _DEFAULT_TIMEOUT_S,
    poll_interval: float = _POLL_INTERVAL_S,
) -> dict[str, Any]:
    """Poll ``qq_chat_history.jsonl`` for a reply referencing *message_id*.

    Reads the chat history file repeatedly until a matching reply is found
    or *timeout* seconds elapse.

    Args:
        workspace: Absolute path to the Partner workspace.
        message_id: The message_id of the injected task.
        timeout: Maximum seconds to wait before giving up.
        poll_interval: Seconds between poll iterations.

    Returns:
        A dict with keys:
        - ``"found"`` (bool): Whether a matching reply was found.
        - ``"reply_content"`` (str): The reply text, or empty string.
        - ``"nlines"`` (int): Total lines read from the chat history.
        - ``"elapsed"`` (float): Seconds spent polling.
        - ``"timed_out"`` (bool): Whether the polling timed out.
    """
    chat_path = _chat_history_path(workspace)
    start = time.monotonic()
    last_size = 0
    reply_content = ""
    nlines = 0

    while True:
        elapsed = time.monotonic() - start
        if elapsed >= timeout:
            logger.debug("[VERIFY] Poll timeout after %.1fs for message_id=%s", elapsed, message_id)
            return {
                "found": False,
                "reply_content": "",
                "nlines": nlines,
                "elapsed": elapsed,
                "timed_out": True,
            }

        if not os.path.exists(chat_path):
            time.sleep(poll_interval)
            continue

        current_size = os.path.getsize(chat_path)
        if current_size == last_size:
            # No new data — wait and retry
            time.sleep(poll_interval)
            continue
        last_size = current_size

        # Read all lines and check for a matching assistant reply
        try:
            with open(chat_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    nlines += 1
                    try:
                        entry = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    # Look for assistant replies that reference our message_id
                    # or have matching content patterns (reply_to, or a proactive response)
                    role = entry.get("role", "")
                    if role != "assistant":
                        continue

                    # Check if this reply references our message
                    reply_to = entry.get("reply_to", "")
                    content = entry.get("content", "")

                    # Match conditions:
                    # 1. Direct reply_to match
                    # 2. Content contains the message_id
                    # 3. It's from a known proactive channel around the task time
                    if message_id in reply_to or message_id in content:
                        reply_content = content
                        elapsed_final = time.monotonic() - start
                        logger.debug(
                            "[VERIFY] Found reply for message_id=%s in %.1fs",
                            message_id, elapsed_final,
                        )
                        return {
                            "found": True,
                            "reply_content": reply_content,
                            "nlines": nlines,
                            "elapsed": elapsed_final,
                            "timed_out": False,
                        }

                    # Fallback: if the assistant entry's source is "proactive" or "self_review"
                    # and was written after our inject time, consider it as a task response
                    # (for agents that don't use reply_to)
                    src = entry.get("source", "")
                    channel = entry.get("channel", "")
                    if src in ("proactive", "self_review", "qq", "desktop_gui") or \
                       channel in ("proactive", "desktop"):
                        # Check timestamp roughly
                        ts_str = entry.get("timestamp", "")
                        if ts_str and len(content) > 20:
                            reply_content = content
                            elapsed_final = time.monotonic() - start
                            logger.debug(
                                "[VERIFY] Matched assistant reply via source=%s for message_id=%s in %.1fs",
                                src, message_id, elapsed_final,
                            )
                            return {
                                "found": True,
                                "reply_content": reply_content,
                                "nlines": nlines,
                                "elapsed": elapsed_final,
                                "timed_out": False,
                            }
        except (OSError, IOError) as exc:
            logger.warning("[VERIFY] Error reading chat history: %s", exc)

        time.sleep(poll_interval)


# ═══════════════════════════════════════════════════════════════════════════════
# Benchmark Execution
# ═══════════════════════════════════════════════════════════════════════════════


async def benchmark_single(
    task_description: str,
    workspace: str,
    *,
    timeout: int = _DEFAULT_TIMEOUT_S,
) -> TaskMetrics:
    """Run a single benchmark task via desktop_inbox injection and measure it.

    The task is submitted to the agent by writing to the desktop_inbox.
    The module then polls the agent's chat history for a reply.

    Args:
        task_description: Natural-language description of the task to run.
        workspace: Absolute path to the Partner workspace (e.g.
            ``/mnt/e/work/partner_workspace/instances/03``).
        timeout: Maximum seconds to wait for a reply (default 120).

    Returns:
        A :class:`TaskMetrics` instance with the measured performance.

    Metrics measured:
        - ``avg_time``: Time (seconds) until a reply was received, or the
          timeout duration if no reply arrived.
        - ``success_rate``: 1.0 if a substantive reply was received, 0.0
          if the task timed out or returned an empty reply.
        - ``error_count``: 0 for success, 1 for timeout/error.
        - ``steps_completed``: 1 if reply found, 0 otherwise.
    """
    # 1. Inject the task
    message_id = _inject_task(workspace, task_description)

    # 2. Poll for reply (synchronous I/O in a thread-safe manner)
    #    Note: file I/O is blocking but fast; for a fully async version
    #    wrap in asyncio.to_thread() if the event loop requires it.
    reply = await _poll_for_reply_async(workspace, message_id, timeout=timeout)

    # 3. Build metrics
    avg_time = reply["elapsed"]
    found = reply["found"]
    content = reply.get("reply_content", "")
    timed_out = reply.get("timed_out", False)

    # Determine success: found a reply with substantive content
    has_substance = found and len(content.strip()) > 50
    success_rate = 1.0 if has_substance else 0.0
    error_count = 0 if has_substance else 1
    steps_completed = 1 if found else 0

    metrics = TaskMetrics(
        task=task_description,
        avg_time=avg_time,
        success_rate=success_rate,
        error_count=error_count,
        steps_completed=steps_completed,
    )

    logger.info(
        "[VERIFY] benchmark_single: task=%.50s | found=%s | elapsed=%.2fs | success=%s",
        task_description, found, avg_time, success_rate == 1.0,
    )
    return metrics


async def _poll_for_reply_async(
    workspace: str,
    message_id: str,
    *,
    timeout: int = _DEFAULT_TIMEOUT_S,
    poll_interval: float = _POLL_INTERVAL_S,
) -> dict[str, Any]:
    """Async wrapper around the synchronous ``_poll_for_reply``.

    Runs the blocking file I/O in a separate thread so the event loop
    is not blocked during polling.

    Args:
        workspace: Absolute path to the Partner workspace.
        message_id: The message_id of the injected task.
        timeout: Maximum seconds to wait.
        poll_interval: Seconds between poll iterations.

    Returns:
        Same dict format as :func:`_poll_for_reply`.
    """
    import asyncio

    def _poll() -> dict[str, Any]:
        return _poll_for_reply(
            workspace, message_id,
            timeout=timeout, poll_interval=poll_interval,
        )

    return await asyncio.to_thread(_poll)


# ═══════════════════════════════════════════════════════════════════════════════
# Full Verification Cycle
# ═══════════════════════════════════════════════════════════════════════════════


async def run_verification(
    plan_id: str,
    benchmark_tasks: list[str],
    workspace: str,
    *,
    timeout: int = _DEFAULT_TIMEOUT_S,
) -> VerificationResult:
    """Run the full before/after verification cycle.

    The cycle:

    1. Run all *benchmark_tasks* and record *before* metrics.
    2. Inject the improvement plan (signal the agent to apply it).
    3. Wait briefly for the improvement to take effect.
    4. Re-run all *benchmark_tasks* and record *after* metrics.
    5. Compare before/after and produce a verdict.

    Args:
        plan_id: Identifier of the improvement plan being verified
            (e.g. ``"plan_001"``).  Used for traceability.
        benchmark_tasks: A list of natural-language task descriptions
            (3-5 tasks recommended) that exercise the capabilities
            targeted by the improvement plan.
        workspace: Absolute path to the Partner workspace.  The
            ``state/desktop_inbox.jsonl`` and
            ``state/qq_chat_history.jsonl`` files must exist here.
        timeout: Maximum seconds to wait for each individual task reply
            (default 120).  The total verification time will be roughly
            ``2 * len(benchmark_tasks) * timeout`` in the worst case.

    Returns:
        A :class:`VerificationResult` with before/after metrics, the
        verdict, and a readable report.
    """
    logger.info(
        "[VERIFY] Starting verification: plan_id=%s | tasks=%d | workspace=%s",
        plan_id, len(benchmark_tasks), workspace,
    )

    # ── Phase 1: Before ────────────────────────────────────────────────────
    before_metrics: list[TaskMetrics] = []
    for task in benchmark_tasks:
        metrics = await benchmark_single(task, workspace, timeout=timeout)
        before_metrics.append(metrics)

    # ── Phase 2: Signal improvement ────────────────────────────────────────
    # Inject a meta-task asking the agent to apply the improvement plan
    await _signal_improvement(plan_id, workspace)

    # Give the agent time to process and apply the improvement
    logger.debug("[VERIFY] Waiting %.1fs for improvement to take effect...", _IMPROVEMENT_INJECT_WAIT_S)
    import asyncio
    await asyncio.sleep(_IMPROVEMENT_INJECT_WAIT_S)

    # ── Phase 3: After ─────────────────────────────────────────────────────
    after_metrics: list[TaskMetrics] = []
    for task in benchmark_tasks:
        metrics = await benchmark_single(task, workspace, timeout=timeout)
        after_metrics.append(metrics)

    # ── Phase 4: Compare & produce verdict ─────────────────────────────────
    stats_before = _aggregate_metrics(before_metrics)
    stats_after = _aggregate_metrics(after_metrics)

    improvements = _compute_improvements(stats_before, stats_after)
    verdict = _determine_verdict(improvements)

    report = _build_report(
        plan_id=plan_id,
        before_metrics=before_metrics,
        after_metrics=after_metrics,
        stats_before=stats_before,
        stats_after=stats_after,
        improvements=improvements,
        verdict=verdict,
    )

    result = VerificationResult(
        plan_id=plan_id,
        before_metrics=before_metrics,
        after_metrics=after_metrics,
        verdict=verdict,
        report=report,
        summary_stats={"before": stats_before, "after": stats_after},
        improvements=improvements,
    )

    logger.info(
        "[VERIFY] Verification complete: plan_id=%s | verdict=%s",
        plan_id, verdict,
    )
    return result


async def _signal_improvement(plan_id: str, workspace: str) -> str:
    """Signal the agent to apply an improvement plan via desktop_inbox.

    Injects a meta-task instructing the agent to apply the plan.

    Args:
        plan_id: The improvement plan identifier (e.g. ``"plan_001"``).
        workspace: Absolute path to the Partner workspace.

    Returns:
        The message_id of the injected signal.
    """
    signal_message = (
        f"[SYSTEM] Apply improvement plan {plan_id} now. "
        f"Execute all changes specified in plan {plan_id} and confirm when done."
    )
    return _inject_task(workspace, signal_message)


# ═══════════════════════════════════════════════════════════════════════════════
# Smoke Test — fast syntax + import verification
# ═══════════════════════════════════════════════════════════════════════════════


async def run_smoke_test(
    plan: dict[str, Any],
    workspace: str,
    *,
    timeout: int = 60,
) -> VerificationResult:
    """Run a quick smoke test to verify a plan's implementation didn't break things.

    This is a fast verification (30-90s) that checks:
    1. Python file syntax (if a .py file was modified)
    2. Module importability (try importing the modified module)
    3. A minimal functional test: inject a simple message and verify Partner responds

    Args:
        plan: The improvement plan that was applied.
        workspace: Partner workspace path.
        timeout: Max seconds for the functional test.

    Returns:
        VerificationResult with before/after metrics (before is the baseline).
    """
    plan_id = plan.get("id", "unknown")
    target_module = plan.get("target_module", "")
    file_path = plan.get("file_path", "")

    from .implementation import _resolve_file_path, PROJECT_ROOT as _PROJECT_ROOT
    resolved_path = file_path or _resolve_file_path(plan)

    logger.info(
        "[VERIFY] Running smoke test for plan %s → %s",
        plan_id, resolved_path,
    )

    # ── Phase 1: Syntax check ──────────────────────────────────────────────
    syntax_ok = True
    syntax_errors: list[str] = []
    if resolved_path and resolved_path.endswith(".py") and os.path.exists(resolved_path):
        try:
            with open(resolved_path, "r", encoding="utf-8") as f:
                content = f.read()
            compile(content, resolved_path, "exec")
            logger.info("[VERIFY] ✅ Syntax check passed for %s", resolved_path)
        except SyntaxError as e:
            syntax_ok = False
            syntax_errors.append(f"Syntax error in {os.path.basename(resolved_path)}: {e}")
            logger.warning("[VERIFY] ❌ Syntax check FAILED: %s", e)

    # ── Phase 2: Import check (try importing the modified file's module) ───
    import_ok = True
    import_errors: list[str] = []
    if syntax_ok and resolved_path and resolved_path.endswith(".py") and os.path.exists(resolved_path):
        try:
            # Derive module name from the path
            rel_path = os.path.relpath(resolved_path, _PROJECT_ROOT)
            module_name = rel_path.replace(os.sep, ".").replace(".py", "").strip(".")
            if module_name:
                import importlib
                importlib.invalidate_caches()
                importlib.import_module(module_name)
                logger.info("[VERIFY] ✅ Import check passed: %s", module_name)
        except Exception as e:
            import_ok = False
            import_errors.append(f"Import failed: {e}")
            logger.warning("[VERIFY] ❌ Import check FAILED: %s", e)

    # ── Phase 3: Functional test (desktop_inbox injection) ─────────────────
    func_before_list: list[TaskMetrics] = []
    func_after_list: list[TaskMetrics] = []
    before_metrics_result: TaskMetrics | None = None
    after_metrics_result: TaskMetrics | None = None

    # Only run functional test if syntax + import checks passed
    if syntax_ok and import_ok:
        test_task = "你好，请回复一个简短的问候"
        logger.info("[VERIFY] Running functional test: '%s'", test_task)

        before_metrics_result = await benchmark_single(test_task, workspace, timeout=timeout)
        func_before_list.append(before_metrics_result)

        import asyncio
        await asyncio.sleep(5)

        after_metrics_result = await benchmark_single(test_task, workspace, timeout=timeout)
        func_after_list.append(after_metrics_result)

    # ── Phase 4: Determine verdict ─────────────────────────────────────────
    all_checks_passed = syntax_ok and import_ok

    before_stats = _aggregate_metrics(func_before_list) if func_before_list else {
        "avg_time": 0.0, "success_rate": 0.0, "error_count": 0.0, "tasks_total": 0.0,
    }
    after_stats = _aggregate_metrics(func_after_list) if func_after_list else {
        "avg_time": 0.0, "success_rate": 0.0, "error_count": 0.0, "tasks_total": 0.0,
    }

    improvements = _compute_improvements(before_stats, after_stats)

    if not all_checks_passed:
        verdict = "regressive"
    elif func_after_list and after_stats.get("success_rate", 0) < before_stats.get("success_rate", 0):
        verdict = "regressive"
    elif func_after_list and after_stats.get("avg_time", 0) > before_stats.get("avg_time", 0) * 1.5:
        verdict = "regressive"  # 50%+ slower
    else:
        verdict = "effective"

    # Build report
    report_lines = [
        f"Smoke Test Report — Plan {plan_id}",
        f"",
        f"File: {resolved_path or '(none)'}",
        f"",
        f"Syntax Check: {'✅ PASS' if syntax_ok else '❌ FAIL'}",
    ]
    if syntax_errors:
        report_lines.extend(f"  - {e}" for e in syntax_errors)
    report_lines.append(f"Import Check: {'✅ PASS' if import_ok else '❌ FAIL'}")
    if import_errors:
        report_lines.extend(f"  - {e}" for e in import_errors)
    if before_metrics_result:
        report_lines.append(f"")
        report_lines.append(f"Functional Test (before):")
        report_lines.append(f"  Response time: {before_metrics_result.avg_time:.1f}s")
        report_lines.append(f"  Success: {'✅' if before_metrics_result.success_rate > 0 else '❌'}")
    if after_metrics_result:
        report_lines.append(f"Functional Test (after):")
        report_lines.append(f"  Response time: {after_metrics_result.avg_time:.1f}s")
        report_lines.append(f"  Success: {'✅' if after_metrics_result.success_rate > 0 else '❌'}")
    report_lines.append(f"")
    report_lines.append(f"Verdict: {verdict.upper()}")
    report = "\n".join(report_lines)

    result = VerificationResult(
        plan_id=plan_id,
        before_metrics=func_before_list,
        after_metrics=func_after_list,
        verdict=verdict,
        report=report,
        summary_stats={"before": before_stats, "after": after_stats},
        improvements=improvements,
    )

    logger.info(
        "[VERIFY] Smoke test complete: plan=%s syntax=%s import=%s verdict=%s",
        plan_id, syntax_ok, import_ok, verdict,
    )
    return result


# ═══════════════════════════════════════════════════════════════════════════════
# Aggregation & Comparison
# ═══════════════════════════════════════════════════════════════════════════════


def _aggregate_metrics(metrics: list[TaskMetrics]) -> dict[str, float]:
    """Aggregate a list of :class:`TaskMetrics` into summary statistics.

    Args:
        metrics: List of individual task metrics.

    Returns:
        Dict with keys ``avg_time``, ``success_rate``, ``error_count``,
        and ``tasks_total``.
    """
    if not metrics:
        return {"avg_time": 0.0, "success_rate": 0.0, "error_count": 0.0, "tasks_total": 0.0}

    n = len(metrics)
    total_time = sum(m.avg_time for m in metrics)
    total_success = sum(m.success_rate for m in metrics)
    total_errors = sum(m.error_count for m in metrics)

    return {
        "avg_time": total_time / n,
        "success_rate": total_success / n,
        "error_count": float(total_errors),
        "tasks_total": float(n),
    }


def _compute_improvements(
    before: dict[str, float],
    after: dict[str, float],
) -> dict[str, float]:
    """Compute before/after deltas for each metric.

    Positive values mean improvement (faster time, higher success rate).
    Negative values mean regression.

    Args:
        before: Summary stats from the *before* run.
        after: Summary stats from the *after* run.

    Returns:
        Dict with keys:
        - ``avg_time_delta``: Change in average time (seconds).
          Negative = faster (improvement).
        - ``avg_time_delta_pct``: Percentage change in average time.
          Negative = faster (improvement).
        - ``success_rate_delta``: Change in success rate (0.0–1.0).
          Positive = improvement.
        - ``success_rate_delta_pct``: Percentage change in success rate.
          Positive = improvement.
        - ``error_count_delta``: Change in error count.
          Negative = fewer errors (improvement).
    """
    before_time = before.get("avg_time", 0.0)
    after_time = after.get("avg_time", 0.0)
    before_rate = before.get("success_rate", 0.0)
    after_rate = after.get("success_rate", 0.0)
    before_errors = before.get("error_count", 0.0)
    after_errors = after.get("error_count", 0.0)

    time_delta = after_time - before_time  # negative = faster (good)
    rate_delta = after_rate - before_rate  # positive = better
    error_delta = after_errors - before_errors  # negative = fewer errors (good)

    time_delta_pct = 0.0
    if before_time > 0:
        time_delta_pct = (time_delta / before_time) * 100.0

    rate_delta_pct = 0.0
    if before_rate > 0:
        rate_delta_pct = (rate_delta / before_rate) * 100.0
    elif after_rate > 0:
        rate_delta_pct = 100.0  # went from 0 to something positive

    return {
        "avg_time_delta": round(time_delta, 3),
        "avg_time_delta_pct": round(time_delta_pct, 1),
        "success_rate_delta": round(rate_delta, 3),
        "success_rate_delta_pct": round(rate_delta_pct, 1),
        "error_count_delta": round(error_delta, 1),
    }


def _determine_verdict(improvements: dict[str, float]) -> str:
    """Determine the verdict based on the computed improvements.

    The verdict is determined by:

    - **effective**: Average time improved by >= 10% AND success rate
      did not degrade by more than 10%.
    - **regressive**: Average time degraded by > 10% OR success rate
      dropped by > 10%.
    - **neutral**: All other cases (changes within the margin of noise).

    Args:
        improvements: Dict returned by :func:`_compute_improvements`.

    Returns:
        One of ``"effective"``, ``"neutral"``, or ``"regressive"``.
    """
    time_pct = improvements.get("avg_time_delta_pct", 0.0)
    rate_delta = improvements.get("success_rate_delta", 0.0)

    # Time improvement is negative (faster after)
    time_improved = time_pct <= -_TIME_IMPROVEMENT_THRESHOLD * 100.0
    time_regressed = time_pct > _TIME_IMPROVEMENT_THRESHOLD * 100.0
    rate_degraded = rate_delta < -_SUCCESS_RATE_DEGRADE_THRESHOLD

    if time_improved and not rate_degraded:
        return "effective"
    if time_regressed or rate_degraded:
        return "regressive"
    return "neutral"


# ═══════════════════════════════════════════════════════════════════════════════
# Report Generation
# ═══════════════════════════════════════════════════════════════════════════════


def generate_report(result: VerificationResult) -> str:
    """Generate a human-readable verification report from a result.

    The report includes:
    - Header with plan ID and timestamp
    - Per-task before/after comparison table
    - Summary statistics
    - Improvement deltas
    - Final verdict with justification

    Args:
        result: A :class:`VerificationResult` from :func:`run_verification`.

    Returns:
        A formatted string suitable for display or saving to a file.
    """
    return result.report if result.report else _build_report(
        plan_id=result.plan_id,
        before_metrics=result.before_metrics,
        after_metrics=result.after_metrics,
        stats_before=result.summary_stats.get("before", {}),
        stats_after=result.summary_stats.get("after", {}),
        improvements=result.improvements,
        verdict=result.verdict,
    )


def _build_report(
    *,
    plan_id: str,
    before_metrics: list[TaskMetrics],
    after_metrics: list[TaskMetrics],
    stats_before: dict[str, float],
    stats_after: dict[str, float],
    improvements: dict[str, float],
    verdict: str,
) -> str:
    """Build the full verification report string.

    Args:
        plan_id: Improvement plan identifier.
        before_metrics: List of before-task metrics.
        after_metrics: List of after-task metrics.
        stats_before: Aggregated before statistics.
        stats_after: Aggregated after statistics.
        improvements: Computed improvement deltas.
        verdict: The final verdict.

    Returns:
        Formatted report string.
    """
    lines: list[str] = []
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    verdict_icon = {"effective": "✅", "neutral": "➡️", "regressive": "⚠️"}.get(verdict, "❓")

    # ── Header ─────────────────────────────────────────────────────────────
    lines.append("=" * 72)
    lines.append("  PARTNER SELF-EVOLUTION — VERIFICATION REPORT")
    lines.append("=" * 72)
    lines.append(f"  Plan ID:      {plan_id}")
    lines.append(f"  Timestamp:    {timestamp}")
    lines.append(f"  Tasks:        {len(before_metrics)}")
    lines.append(f"  Verdict:      {verdict_icon}  {verdict.upper()}")
    lines.append("")

    # ── Per-task Comparison ─────────────────────────────────────────────────
    lines.append("-" * 72)
    lines.append("  PER-TASK COMPARISON")
    lines.append("-" * 72)
    header = f"  {'Task':<40s} {'Before(s)':>10s} {'After(s)':>10s} {'Status':>10s}"
    lines.append(header)
    lines.append("  " + "-" * 72)

    for i in range(max(len(before_metrics), len(after_metrics))):
        before = before_metrics[i] if i < len(before_metrics) else None
        after = after_metrics[i] if i < len(after_metrics) else None

        task_label = ""
        before_time = 0.0
        after_time = 0.0
        status = ""

        if before and after:
            # Truncate task description for display
            task_label = before.task[:38] + ".." if len(before.task) > 40 else before.task
            before_time = before.avg_time
            after_time = after.avg_time
            # Determine per-task direction
            if after.success_rate > before.success_rate:
                status = "✅"
            elif after.success_rate < before.success_rate:
                status = "⚠️"
            elif after.avg_time < before.avg_time * 0.9:
                status = "✅"
            elif after.avg_time > before.avg_time * 1.1:
                status = "⚠️"
            else:
                status = "➡️"
        elif before:
            task_label = before.task[:38] + ".." if len(before.task) > 40 else before.task
            before_time = before.avg_time
            status = "❌ (after missing)"
        elif after:
            task_label = after.task[:38] + ".." if len(after.task) > 40 else after.task
            after_time = after.avg_time
            status = "❌ (before missing)"

        lines.append(f"  {task_label:<40s} {before_time:>8.2f}s {after_time:>8.2f}s {status:>10s}")

    lines.append("")

    # ── Summary Statistics ─────────────────────────────────────────────────
    lines.append("-" * 72)
    lines.append("  SUMMARY STATISTICS")
    lines.append("-" * 72)
    _add_stat_line(lines, "Average time (s)", stats_before.get("avg_time", 0.0), stats_after.get("avg_time", 0.0))
    _add_stat_line(lines, "Success rate", stats_before.get("success_rate", 0.0), stats_after.get("success_rate", 0.0), is_pct=True)
    _add_stat_line(lines, "Error count", stats_before.get("error_count", 0.0), stats_after.get("error_count", 0.0))
    lines.append("")

    # ── Improvement Deltas ─────────────────────────────────────────────────
    lines.append("-" * 72)
    lines.append("  IMPROVEMENT DELTAS")
    lines.append("-" * 72)
    _add_delta_line(lines, "Avg time delta", improvements.get("avg_time_delta", 0.0), "s", lower_better=True)
    _add_delta_line(lines, "Avg time delta (%)", improvements.get("avg_time_delta_pct", 0.0), "%", lower_better=True)
    _add_delta_line(lines, "Success rate delta", improvements.get("success_rate_delta", 0.0), "", lower_better=False)
    _add_delta_line(lines, "Error count delta", improvements.get("error_count_delta", 0.0), "count", lower_better=True)
    lines.append("")

    # ── Verdict ────────────────────────────────────────────────────────────
    lines.append("=" * 72)
    lines.append(f"  VERDICT: {verdict_icon}  {verdict.upper()}")
    lines.append("=" * 72)

    if verdict == "effective":
        lines.append("")
        lines.append("  The improvement plan produced measurable gains:")
        time_delta = improvements.get("avg_time_delta_pct", 0.0)
        rate_delta = improvements.get("success_rate_delta", 0.0)
        if time_delta < 0:
            lines.append(f"    - Execution time reduced by {abs(time_delta):.1f}%")
        if rate_delta > 0:
            lines.append(f"    - Success rate improved by {rate_delta * 100:.1f}%")
        lines.append("")
        lines.append("  Conclusion: The improvement should be retained.")

    elif verdict == "neutral":
        lines.append("")
        lines.append("  The improvement plan produced no significant change:")
        time_delta = improvements.get("avg_time_delta_pct", 0.0)
        rate_delta = improvements.get("success_rate_delta", 0.0)
        lines.append(f"    - Average time changed by {time_delta:+.1f}%")
        lines.append(f"    - Success rate changed by {rate_delta:+.3f}")
        lines.append("")
        lines.append("  Conclusion: The improvement is within the noise margin.")
        lines.append("  Consider collecting more data or refining the improvement.")

    elif verdict == "regressive":
        lines.append("")
        lines.append("  The improvement plan caused degradation:")
        time_delta = improvements.get("avg_time_delta_pct", 0.0)
        rate_delta = improvements.get("success_rate_delta", 0.0)
        if time_delta > 0:
            lines.append(f"    - Execution time increased by {time_delta:.1f}%")
        if rate_delta < 0:
            lines.append(f"    - Success rate dropped by {abs(rate_delta) * 100:.1f}%")
        lines.append("")
        lines.append("  Conclusion: The improvement should be rolled back or revised.")

    lines.append("")
    lines.append("-" * 72)
    lines.append("  End of report")
    lines.append("")

    return "\n".join(lines)


def _add_stat_line(lines: list[str], label: str, before_val: float, after_val: float, *, is_pct: bool = False) -> None:
    """Add a summary statistics line to the report."""
    fmt = ".3f" if not is_pct else ".1%"
    if is_pct:
        b_str = f"{before_val:.1%}"
        a_str = f"{after_val:.1%}"
    else:
        b_str = f"{before_val:.3f}"
        a_str = f"{after_val:.3f}"
    lines.append(f"  {label:<25s}  Before: {b_str:>10s}  After: {a_str:>10s}")


def _add_delta_line(lines: list[str], label: str, value: float, unit: str, *, lower_better: bool) -> None:
    """Add an improvement delta line with direction indicator."""
    if lower_better:
        direction = "↓" if value < 0 else ("↑" if value > 0 else "—")
    else:
        direction = "↑" if value > 0 else ("↓" if value < 0 else "—")
    sign = "+" if value > 0 else ""
    lines.append(f"  {label:<25s}  {sign}{value:.3f} {unit:<6s} {direction}")
